// app/components/Truss.tsx
import { useState } from "react";
import Button from "@/app/components/Button";
import { ArrowClockwise, TrashSimple } from "@phosphor-icons/react";

export default function Truss({ width, onRemove }: { width: number, onRemove?: () => void }) {
  const [controls, setControls] = useState(false);
  const [rotation, setRotation] = useState(0);

  function rotate() {
    setRotation(rotation + 90);
  }

  return (
    <div className="Truss" style={{width: width, height: "62px", position: "relative", rotate: `${rotation}deg`}}>
      <div className={`absolute top-0 left-0 right-0 flex justify-center gap-1 h-[29px] ${controls ? '' : 'hidden'}`}>
        <Button title="Rotate" icon={ArrowClockwise} width="29px" height="29px" iconSize={15} onClick={rotate} />
        <Button title="Remove" icon={TrashSimple} width="29px" height="29px" iconSize={15} onClick={onRemove} />
      </div>

      <div
      className="absolute bottom-0 left-0 right-0 flex justify-center items-center bg-[var(--gray)] h-[29px]" 
      onContextMenu={e => {
        e.preventDefault();
        setControls(!controls);
      }}>
        <p>{width}</p>
      </div>
    </div>
  );  
}

// components/Truss.vue
<script setup>
import { PhArrowClockwise, PhTrashSimple } from '@phosphor-icons/vue'

const props = defineProps({
  width: Number,
  id: Number,
  x: Number,
  y: Number
})

const emit = defineEmits(['remove', 'edge'])

const hidden = ref('hidden')
const rotation = ref(0)

function rotate() {
  rotation.value += 90
}

function remove() {
  emit('remove')
}

function edge(side) {
  emit('edge', { side, id: props.id })
}

function toggleActions() {
  hidden.value = hidden.value === '' ? 'hidden' : ''
}
</script>

<template>
  <div :style="{
    width: props.width + 16 + 'px',
    transform: `rotate(${rotation}deg)`,
    position: 'absolute',
    left: `${props.x}px`,
    top: `${props.y}px` }">
      <div class="actions" :class="hidden">
        <Button title="Rotate" :tag="PhArrowClockwise" :width="29" :height="29" :iconSize="15" @click="rotate" />
        <Button title="Remove" :tag="PhTrashSimple" :width="29" :height="29" :iconSize="15" @click="remove" />
      </div>

      <div class="truss" :id="`truss-${id}`" :style="{ width: props.width + 16 + 'px' }">
        <div
          class="element"
          :style="{ width: props.width + 'px' }"
          @click.right.prevent="toggleActions">
            <p>{{ props.width }}</p>
        </div>

        <button class="edge right" @click="() => edge('right')"></button>
      </div>
  </div>
</template>

<style scoped>
.truss {
  display: flex;
  cursor: pointer;
}

.actions {
  height: 29px;
  display: flex;
  justify-content: center;
  gap: 10px;
}

.element {
  height: 29px;
  background-color: gray;
  text-align: center;
}

p {
  margin: 0;
}

.edge {
  background-color: #1919cc;
  width: 8px;
  padding: 0;
}

.hidden {
  opacity: 0;
}
</style>
