// pages/new/index.vue
<script setup>
import html2canvas from 'html2canvas'
import { PhListNumbers, PhDownloadSimple, PhPlus } from '@phosphor-icons/vue'
import list from './public/list.json'

const trusses = ref([])
let nextId = 0

const parentTruss = ref(null)
const selectedSide = ref(null)

function addTruss(item) {
  const newTruss = { ...item, id: nextId++ }

  if(parentTruss.value && selectedSide.value) {
    const index = trusses.value.findIndex(t => t.id === parentTruss.value.id)
    newTruss.x = selectedSide.value === 'left'
      ? parentTruss.value.x - parentTruss.value.width - 16
      : parentTruss.value.x + parentTruss.value.width + 16
    newTruss.y = parentTruss.value.y
    trusses.value.splice(selectedSide.value === 'left' ? index : index + 1, 0, newTruss)
  } else {
    newTruss.x = 25
    newTruss.y = 75
    trusses.value.push(newTruss)
  }

  // Close dialog after picking truss
  listDialog.close()

  // Clear out the data
  parentTruss.value = null
  selectedSide.value = null
}

function removeTruss(id) {
  trusses.value = trusses.value.filter(truss => truss.id !== id)
}

const trussCount = computed(() => {
  const counts = {}
  trusses.value.forEach(truss => {
    counts[truss.title] = (counts[truss.title] || 0) + 1
  })

  return Object.entries(counts)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([title, count]) => `${count}x ${title}`)
})

async function download() {
  try {
    const image = await html2canvas(document.querySelector('#canvas'))
    const link = document.createElement('a')

    link.download = 'truss_tool-image.png'
    link.href = image.toDataURL('image/png')
    link.click()
  } catch(error) {
    console.error(error)
  }
}

function openListDialog(side, trussId) {
  // Set data
  parentTruss.value = trusses.value.find(t => t.id === trussId)
  selectedSide.value = side

  listDialog.showModal()
}

const showStartProject = computed(() => trusses.value.length === 0)
</script>

<template>
    <nav>
        <Button title="Show details" :tag="PhListNumbers" onclick="details.showModal()" />
        <Button title="Download an image of current canvas" :tag="PhDownloadSimple" @click="download" /> <!-- Doesn't work on Linux, works on Mac (???) -->
    </nav>

  <div id="canvas" :class="{ center: showStartProject }">
    <div v-if="showStartProject" class="startProject center">
      <Button title="Add truss" :tag="PhPlus" @click="openListDialog(null, null)" />
      <p>Start your project by adding the first truss</p>
    </div>

    <Truss
      v-for="truss in trusses"
      v-bind="truss"
      @remove="removeTruss(truss.id)"
      @edge="({ side, id }) => openListDialog(side, id)"
      :key="truss.id"
    />
  </div>

  <Dialog title="Elements" id="listDialog">
    <div id="list_bottom">
      <ListButton
        v-for="(item, index) in list.items"
        :item="item"
        @click="addTruss(item)"
        :key="index"
      />
    </div>
  </Dialog>

  <Dialog title="Details" id="details">
    <p v-for="(item, index) in trussCount" :key="index">{{ item }}</p>
  </Dialog>
</template>

<style>
@import url("~/assets/css/styles.css");

nav {
  display: flex;
  gap: 12px;
  padding: 12px;
}

#list_bottom {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  margin-top: 8px;
}

#canvas {
  background-color: var(--black);
  height: calc(100vh - 88px);
}

.center {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
</style>

// app/new/page.tsx
"use client";

import { useRef, useState } from "react";
import Button from "@/app/components/Button";
import Truss from "@/app/components/Truss";
import Dialog from "@/app/components/Dialog";
import { ArrowLeft, ListNumbers, DownloadSimple, Plus } from "@phosphor-icons/react";
import { generateId } from "@/app/utils/math";
import list from "@/public/list.json";
import Image from "next/image";

interface Truss {
  width: number;
  id: number;
}

export default function NewProject() {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const [trusses, setTrusses] = useState<Truss[]>([]);

  function removeTruss(id: number) {
    setTrusses(trusses.filter(truss => truss.id !== id));
  }
  
  return (
    <>
      <nav className="nav_left gap-3 mb-4">
        <Button title="Go back" icon={ArrowLeft} path="/" />
        <Button title="Show details" icon={ListNumbers} />
        <Button title="Download an image of current canvas" icon={DownloadSimple} />
      </nav>

      {/* Display only when there's no truss */}
      {trusses.length === 0 && 
      <div className="flex flex-col flex-1 items-center justify-center gap-3">
        <Button icon={Plus} onClick={() => dialogRef.current?.showModal()} />
        <p>Start your project by adding the first truss</p>
      </div>}

      <div className="Canvas">
        {trusses.map(truss => {
          return <Truss key={truss.id} width={truss.width} onRemove={() => removeTruss(truss.id)} />
        })}
      </div>

      <Dialog title="Elements" ref={dialogRef}>
        <div className="grid grid-cols-3">
          {list.items.map(item => (
            <button 
            key={item.id} 
            className="flex m-2" 
            onClick={() => {
              setTrusses([...trusses, {width: item.width, id: generateId()}]);
              dialogRef.current?.close();
            }}>
              <Image src={`/truss/${item.width}.jpg`} alt={`Truss ${item.width}`} width={80} height={80} className="rounded-lg" />

              <div className="text-left ml-2">
                <h2>{item.title}</h2>
                <p>{item.width}x29cm</p>
                <p>{item.weight}kg</p>
              </div>              
            </button>
          ))}
        </div>
      </Dialog>
    </>
  );
}
